[workspace]
resolver = "2"
members = [
    "crates/krama_cli",
    "crates/krama_core",
    "crates/krama_macro",
    "crates/krama_runtime",
    "crates/krama_std",
]

[workspace.package]
authors = ["dannycreations"]
edition = "2021"
license = "GPL"
repository = "https://github.com/dannycreations/Krama"

[workspace.dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
ariadne = { version = "0.6.0", features = ["auto-color"] }
bumpalo = { version = "3.19.1", features = ["collections", "boxed"] }
clap = { version = "4.5.53", features = ["derive"] }
derive_more = { version = "2.1.0", features = ["full"] }
futures = "0.3.31"
krama_core = { path = "crates/krama_core" }
krama_macro = { path = "crates/krama_macro" }
krama_runtime = { path = "crates/krama_runtime" }
krama_std = { path = "crates/krama_std" }
linkme = "0.3.35"
logos = "0.16.0"
path-clean = "=1.0.1"
proc-macro2 = "1.0.103"
quote = "1.0.42"
strum = "0.27.2"
strum_macros = "0.27.2"
syn = "2.0.111"
thiserror = "2.0.17"
tokio = { version = "1.48.0", default-features = false }
walkdir = "=2.5.0"

[profile.dev]
codegen-units = 16
debug = 1
incremental = true

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = false
lto = true
opt-level = "z"
panic = "abort"
split-debuginfo = "packed"
