[package]
name = "krama_std"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
bumpalo.workspace = true
futures.workspace = true
inventory.workspace = true
krama_core = { path = "../krama_core" }
krama_macro = { path = "../krama_macro" }
once_cell.workspace = true
phf.workspace = true
rustc-hash.workspace = true
tokio.workspace = true

[dev-dependencies]
krama_runtime = { path = "../krama_runtime" }
